Repository Amna-Hassan04/Serenity-Guide, pull requests merged in 2024-10, with the labels that each got.

#16 #Add Greetings Bot
  .github/workflows/greetings.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#4 Update app.py
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#48 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#19 Soothing Sounds bug fixes, Added Audio Controls
  README.md
  app.py
  requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#47 Pr template.md
  .github/pr_template.md
  .github/workflows/check_screenshot.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#42 Correct Username in git clone Command (Issue #33)
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#26 In the Read Me File: Fixed the wrong link in Contributer Table and changed the table style
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#18 Fixed the wrong link in Contributor Table and changed the table to look like the attached sample.
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#56 scroll up to top button added
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#52 Resolved Broken URL in Code of Conduct Link
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#36 Fix incorrect username in git clone command #33 Fixed
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#45 Documentation and license
  DOCUMENTATION.md
  license.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#54 Added import datetime in codebase
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#72 Text replacement to "SereniFi"
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#71 issues resolved
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#70 Added progress bar in Daily Challenges Suggestions in Calm Space
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#100 Github Issue Template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#87 Updated README.md, solved Issue 82
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#110 updting top button bug
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#133 Db integration tips
  .gitignore
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#142 Spotify playlists embedded using IFrame API
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#146 PR has the latest version of the project
  .github/workflows/check-up-to-date.yml
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#124 Blue Link Visibility Issue Solved
  .gitignore
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#157 Create anouncement.yml
  .github/ISSUE_TEMPLATE/anouncement.yml
Labels: hacktoberfest-accepted, hacktoberfest

#143 Updated resource page with all the features
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#156 (issue : [FEATURE] - Create an FAQs Page #105) added FAQs page
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#188 fix website not opening issue
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#172 Added "Simon Game Challenge" under Mood-Boosting Games
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#204 Logging and Exception handling added
  DOCUMENTATION.md
  app.py
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
